name: Update an entity
description: Report that an existing entity has changed the term they use
title: "Update: [entity name]"
labels: ["update"]
body:
  - type: input
    id: entity_name
    attributes:
      label: Entity name
      description: The name of the existing entity to update
      placeholder: e.g. Apple
    validations:
      required: true

  - type: textarea
    id: what_changed
    attributes:
      label: What changed?
      description: Describe what is different (e.g. "They now use 'Chinese New Year' instead of 'Lunar New Year'")
    validations:
      required: true

  - type: textarea
    id: source_urls
    attributes:
      label: New source URL(s)
      description: Public link(s) to the updated source — one URL per line
      placeholder: |
        https://example.com/source1
        https://example.com/source2
    validations:
      required: true

  - type: input
    id: captured_on
    attributes:
      label: Captured date
      description: When you captured this (YYYY-MM-DD)
      placeholder: "2026-01-29"
    validations:
      required: true

  - type: textarea
    id: evidence
    attributes:
      label: Evidence
      description: Upload a screenshot if available (optional). Drag and drop an image here.
